version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: orca
    binary: orca
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: orca
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

dockers_v2:
  - images:
      - "ghcr.io/orc-analytics/core"

    tags:
      - "{{ .Version }}"

    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
    ids:
      - orca

release:
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
  
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
